# Generated by Django 2.2.16 on 2022-02-24 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220222_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.Title', validators=[django.core.validators.MinLengthValidator(1, message='xxx')], verbose_name='Отзыв'),
        ),
    ]
