# Generated by Django 2.2.16 on 2022-02-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220227_1651'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='Unique review',
        ),
    ]
